backend:
  name: github
  repo: Alfiandi-ux/alfiandi-ux.github.io
  branch: main
  auth_type: pkce
  base_url: https://auth.decapbridge.com
  auth_endpoint: /sites/addda0f6-73fc-4e06-8650-8a2949633fc9/pkce
  auth_token_endpoint: /sites/addda0f6-73fc-4e06-8650-8a2949633fc9/token

logo_url: https://decapbridge.com/decapcms-with-bridge.svg
site_url: https://alfiandi-ux.github.io

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "tulisan"
    label: "Tulisan"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Cover Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
